### ISSUE TITLE
Mutation gets erroneously marked as killed

### ISSUE THREAD

**Issue by hknutzen** [go-gremlins/gremlins#184] opened 2022-10-04 21:46 UTC
### Bug Description

I run gremlins in integration mode.
When run on the whole project, a mutation gets correctly marked as LIVED.
But when run on the package where the mutated files is located, the same mutation is marked as KILLED by mistake.

### To Reproduce

1. `git clone -b gremlins-issue-184 https://github.com/hknutzen/Netspoc.git`
2. `cd Netspoc/go`
3. #for simplicity, only enable one mutation: "Invert logical operators"
 `cat > .gremlins.yml <<END`
```
mutants:
  arithmetic-base:
    enabled: false
  conditionals-boundary:
    enabled: false
  conditionals-negation:
    enabled: false
  increment-decrement:
    enabled: false
  invert-negatives:
    enabled: false
  invert-logical:
    enabled: true
  invert-loopctrl:
    enabled: false
  invert-bitwise:
    enabled: false
END
```

4. gremlins run -i --coverpkg ./pkg/...
 shows:
```
Starting...
Gathering coverage... done in 18.834607584s
      KILLED INVERT_LOGICAL at pkg/api/modify.go:199:42
      KILLED INVERT_LOGICAL at pkg/api/modify.go:199:21
      KILLED INVERT_LOGICAL at pkg/api/modify.go:200:19
      KILLED INVERT_LOGICAL at pkg/api/modify.go:256:17
  NOT VIABLE INVERT_LOGICAL at pkg/api/path.go:249:23
      KILLED INVERT_LOGICAL at pkg/api/path.go:250:49
      KILLED INVERT_LOGICAL at pkg/api/path.go:250:21
       LIVED INVERT_LOGICAL at pkg/api/path.go:394:26  #OK
     ... <-- process may be interrupted now
```
5. cd pkg/api
6. gremlins run -i --coverpkg ./pkg/...
 shows:
```
Starting...
Gathering coverage... done in 18.470632631s
      KILLED INVERT_LOGICAL at modify.go:199:42
      KILLED INVERT_LOGICAL at modify.go:199:21
      KILLED INVERT_LOGICAL at modify.go:200:19
      KILLED INVERT_LOGICAL at modify.go:256:17
      KILLED INVERT_LOGICAL at path.go:249:23
      KILLED INVERT_LOGICAL at path.go:250:49
      KILLED INVERT_LOGICAL at path.go:250:21
      KILLED INVERT_LOGICAL at path.go:394:26  #BAD
  ....
```

### Found behaviour

Gremlins marks line `pkg/api/path.go:394:26` as LIVED, when run on the whole project,
but it marks the same line as KILLED, when run in directory `pkg/api`.

### Expected behaviour

Line `path.go:394:26` should in both cases be marked as LIVED.

### Operating System

- OS: Ubuntu
- Version 22.04.1

**Comment by hknutzen** [comment] 2022-10-06 19:26
When adding flag `--test-cpu 1` to the command that is run in directory `pkg/api`, the output changes to
```
~/Netspoc/go/pkg/api$ gremlins run -i --coverpkg ./pkg/... --test-cpu 1
Starting...
Gathering coverage... done in 10.599028182s
       LIVED INVERT_LOGICAL at modify.go:199:42
       LIVED INVERT_LOGICAL at modify.go:199:21
       LIVED INVERT_LOGICAL at modify.go:200:19
       LIVED INVERT_LOGICAL at modify.go:256:17
  NOT VIABLE INVERT_LOGICAL at path.go:249:23
       LIVED INVERT_LOGICAL at path.go:250:49
       LIVED INVERT_LOGICAL at path.go:250:21
       LIVED INVERT_LOGICAL at path.go:394:26

Mutation testing completed in 6 seconds 836 milliseconds
Killed: 0, Lived: 7, Not covered: 0
Timed out: 0, Not viable: 1
Test efficacy: 0.00%
Mutator coverage: 100.00%
```

**Comment by hknutzen** [comment] 2022-10-06 19:31
Note that gremlins finishes surprisingly fast, when all mutations are erroneously marked as KILLED:
```
~/Netspoc/go/pkg/api$ gremlins run -i --coverpkg ./pkg/... 
Starting...
Gathering coverage... done in 11.582980452s
      KILLED INVERT_LOGICAL at modify.go:199:42
      KILLED INVERT_LOGICAL at modify.go:199:21
      KILLED INVERT_LOGICAL at modify.go:200:19
      KILLED INVERT_LOGICAL at modify.go:256:17
      KILLED INVERT_LOGICAL at path.go:249:23
      KILLED INVERT_LOGICAL at path.go:250:49
      KILLED INVERT_LOGICAL at path.go:250:21
      KILLED INVERT_LOGICAL at path.go:394:26

Mutation testing completed in 450 milliseconds 209 microseconds
Killed: 8, Lived: 0, Not covered: 0
Timed out: 0, Not viable: 0
Test efficacy: 100.00%
Mutator coverage: 100.00%
```

**Comment by k3rn31** [comment] 2022-10-07 04:59
I'll try to work on this during the weekend, unless someone wants to take a look earlier (@giose86, @giorgiaroccetti 😄?).

Have you already tried to reproduce it manually? If you perform the same tests as Gremlins would, do the tests fail in both cases?

The fast execution time makes me think that with that configuration it is not even executing the tests.

Regarding the `--test-cpu 1`, it is highly probable that this gives strange results (I was even unsure about making it available as a config param). That means all the test will run on a single CPU. I would rather expect timeouts rather than LIVED, though. We should experiment more with these parameters.

**Comment by hknutzen** [comment] 2022-10-09 18:31
I analyzed the case where mutations are KILLED fast and erroneously with a debugger.
Interesting are these lines:
https://github.com/go-gremlins/gremlins/blob/95a86d531ed13fe8730bdd44e3406086d37b15ad/internal/engine/executor.go#L206-L215
```
cd ~/Netspoc/go/pkg/api
dlv exec ~/go/bin/gremlins -- run -i --coverpkg ./pkg/... --workers 1
#set a breakpoint at line 213.
b /home/hk/gremlins/internal/engine/executor.go:213
# start 
c
#stops at line 213 (deadline wasn't exceeded)
#look at value of variable err
p err
error(*os/exec.ExitError) *{
	ProcessState: *os.ProcessState {
		pid: 52061,
		status: 256,
		rusage: *(*syscall.Rusage)(0xc0000fa7e0),},
	Stderr: []uint8 len: 0, cap: 0, nil,}
#extit status seems to be 1
#then show variable 'cmd' with executed commad and working directory
p cmd
...
	Args: []string len: 6, cap: 6, [
		"go",
		"test",
		"-timeout",
		"34.438129655s",
		"-failfast",
		"./pkg/api/...",
	],
...
	Dir: "/tmp/gremlins-1816756920/wd-3088232965/pkg/api",
```
When running the same command manually in the same directory, the exit status is zero:
```
cd /tmp/gremlins-1816756920/wd-3088232965
go test -timeout 34.438129655s -failfast ./pkg/api/...
?   	github.com/hknutzen/Netspoc/go/pkg/api	[no test files]
echo $?
0
```
I don't understand, what causes gremlins to get an exit value of 1 in this case, where no test files are run.

**Comment by hknutzen** [comment] 2022-10-09 18:42
From my debugging session we see, that gremlins runs `go test` with argument `./pkg/api/...`.
But in integration mode I expected an argument `./...`, since all tests should be run.
When starting gremlins inside a subdirectory of a module, I would expect that mutations are only applied to files inside this subdirectory, but that integration mode still applies all tests of the whole module.

I think in this code
https://github.com/go-gremlins/gremlins/blob/95a86d531ed13fe8730bdd44e3406086d37b15ad/internal/engine/executor.go#L236-L241
lines 238 to 240 should be deleted.

**Comment by k3rn31** [comment] 2022-10-10 03:45
I didn't have time to check during the weekend, but it is possible we have a problem there. I might have introduced a bug when working on the parallel execution.

**Comment by k3rn31** [comment] 2022-10-11 08:20
@giose86 will take care of this.

**Comment by giose86** [comment] 2022-10-12 19:37
Hi @hknutzen,
the mutations are erroneously marked as KILLED because the command:
`gremlins run -i --coverpkg ./pkg/...` (from pkg/api) under the hood it runs the command `go test -timeout 4.614464024s -failfast ./pkg/api/...` reporting this error: _pattern ./pkg/api/...: lstat ./pkg/api/: no such file or directory_
so it's the go test command itself getting error.

By making the tweaks suggested by you, now it reports all the mutations as LIVED...so weird...
i will investigate...

**Comment by hknutzen** [comment] 2022-10-12 19:46
OK, when I did run the test command manually, I didn't realize, that it was run from pkg/api .
For my suggested change I assumed it will be run from module root.

**Comment by giose86** [comment] 2022-10-17 16:26
i got the problem: the **cmd.Dir** 
https://github.com/go-gremlins/gremlins/blob/95a86d531ed13fe8730bdd44e3406086d37b15ad/internal/engine/executor.go#L202

 should be set with the **rootDir** got from line
https://github.com/go-gremlins/gremlins/blob/95a86d531ed13fe8730bdd44e3406086d37b15ad/internal/engine/executor.go#L165

since when we are in integration mode, the working directory of the **cmd** has to be set to the root working directory under evaluation. Also the lines 238 to 240
https://github.com/go-gremlins/gremlins/blob/95a86d531ed13fe8730bdd44e3406086d37b15ad/internal/engine/executor.go#L236-L241
should be removed, as suggested by @hknutzen.

@k3rn31 does this make sense to you?

**Comment by k3rn31** [comment] 2022-10-17 16:31
Yes, it does. Let’s provide the fix and test it. Maybe it is the case for a 0.4.1 release.Message ID: ***@***.***>

**Closed** 2022-10-26 07:45 UTC
Labels: c/bug
