### ISSUE TITLE
[request] Is there a way to filter out folders from mutations/results?

### ISSUE THREAD

**Issue by corentinmusard** [go-gremlins/gremlins#227] opened 2024-02-04 16:36 UTC
# 🚀 Feature Request

### Is your feature request related to a problem? Please describe

gremlins is showing `NOT COVERED` for generated code. I don't want to make it mutate generated code and see that in the report.

### Describe the solution you'd like

A `--except` flag that can be use like `--except "./protogen/..."`

Or automatically detect generated code, protogen code have this comment on every file:

```go
// Code generated by protoc-gen-go. DO NOT EDIT.
```

**Comment by rusinikita** [comment] 2024-02-11 11:17
Hi @corentinmusard ! Feature request already exists its #193

Please, check PR and provide feedback if it fits you #228

If you need this feature fast you can use my fork.

**Comment by k3rn31** [comment] 2024-02-12 10:25
This is a duplicate of #193, I'll close this and we continue tracking there.

**Closed by k3rn31** 2024-02-12 10:25 UTC
Labels: c/feature
